import streamlit as st
import os
import requests
from bs4 import BeautifulSoup
from groq import Groq
from dotenv import load_dotenv
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import time

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
EMAIL_SENDER = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")

client = Groq(api_key=GROQ_API_KEY)

st.set_page_config(page_title="AutoAgent 🤖", page_icon="🤖")
st.title("🤖 AutoAgent — Autonomous Research Assistant")
st.write("Give me a topic. I'll search the web, read sources, and send you a professional report.")

topic = st.text_input("🔍 What should I research?", placeholder="e.g. Tesla automation strategy 2026")
email_receiver = st.text_input("📧 Send report to:", placeholder="your@email.com")

def search_web(query):
    st.write("🔍 Searching the web...")
    headers = {"User-Agent": "Mozilla/5.0"}
    # Use Google search instead
    url = f"https://www.google.com/search?q={query.replace(' ', '+')}"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    results = []
    for result in soup.find_all("div", class_="tF2Cxc"):
        title_el = result.find("h3")
        link_el = result.find("a")
        if title_el and link_el:
            title = title_el.get_text()
            link = link_el.get("href")
            if link and link.startswith("http"):
                results.append({"title": title, "url": link})
    # Fallback — use hardcoded news sources for the topic
    if not results:
        results = [
            {"title": f"Wikipedia: {query}", "url": f"https://en.wikipedia.org/wiki/{query.replace(' ', '_')}"},
            {"title": f"BBC News: {query}", "url": f"https://www.bbc.co.uk/search?q={query.replace(' ', '+')}"},
        ]
    return results

def scrape_page(url):
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers, timeout=5)
        soup = BeautifulSoup(response.text, "html.parser")
        paragraphs = soup.find_all("p")
        text = " ".join([p.get_text() for p in paragraphs[:20]])
        return text[:3000]
    except:
        return ""

def research_topic(topic):
    results = search_web(topic)
    all_content = ""
    
    for i, result in enumerate(results[:3]):
        st.write(f"📖 Reading source {i+1}: {result['title'][:50]}...")
        content = scrape_page(result["url"])
        if content:
            all_content += f"\n\nSource: {result['title']}\n{content}"
        time.sleep(1)
    
    return all_content, results

def generate_report(topic, content):
    st.write("🧠 Analyzing and writing report...")
    prompt = f"""You are a professional research analyst. Based on the web content below, write a comprehensive, well-structured report about: {topic}

The report should have:
1. Executive Summary (3-4 sentences)
2. Key Findings (5-7 bullet points)
3. Detailed Analysis (3-4 paragraphs)
4. Conclusions & Implications

Web content gathered:
{content[:6000]}

Write the report in a professional tone. Be specific and cite interesting facts."""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1500
    )
    return response.choices[0].message.content

def send_report(report, topic, receiver):
    st.write("📧 Sending report to your inbox...")
    html = f"""
    <html><body style="font-family: Arial; padding: 20px; max-width: 800px;">
        <h1>🤖 AutoAgent Research Report</h1>
        <h2>Topic: {topic}</h2>
        <hr>
        <div style="white-space: pre-wrap;">{report}</div>
        <hr>
        <p style="color: gray;">Generated by AutoAgent — Autonomous Research Assistant</p>
    </body></html>
    """
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🤖 AutoAgent Report: {topic}"
    msg["From"] = EMAIL_SENDER
    msg["To"] = receiver
    msg.attach(MIMEText(html, "html"))
    
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, receiver, msg.as_string())

if st.button("🚀 Start Research") and topic and email_receiver:
    st.markdown("---")
    st.markdown("### 🤖 Agent Running...")
    
    with st.status("AutoAgent is working...", expanded=True):
        content, sources = research_topic(topic)
        
        if not content:
            st.error("Couldn't scrape enough content. Try a different topic.")
        else:
            report = generate_report(topic, content)
            
            st.markdown("---")
            st.markdown("### 📊 Report Preview")
            st.markdown(report)
            
            try:
                send_report(report, topic, email_receiver)
                st.success(f"✅ Report sent to {email_receiver}!")
            except Exception as e:
                st.warning(f"Report generated but email failed: {e}")
                st.info("Copy the report above manually.")
    
    st.balloons()